global:
  addPrometheusAnnotations: true

server:
  ingress:
    enabled: false

controller:
  metrics:
    enabled: true

repoServer:
  metrics:
    enabled: true

server:
  metrics:
    enabled: true

dex:
  metrics:
    enabled: true

redis:
  metrics:
    enabled: true

applicationSet:
  metrics:
    enabled: true

notifications:
  metrics:
    enabled: true
