apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    # Alternatively, we could use the git directory generator here intead
    - list:
        elements:
          - env: prod
          - env: staging
  template:
    metadata:
      name: guestbook-{{ .env }}
    spec:
      project: default
      source:
        repoURL: https://github.com/abourn/argo-cd-demo.git
        targetRevision: HEAD
        path: manifests/guestbook/{{ .env }}
      destination:
        namespace: guestbook-{{ .env }}
        server: https://kubernetes.default.svc
