apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: contour
  namespace: argocd
spec:
  destination:
    namespace: contour
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/contour
    repoURL: https://github.com/abourn/argo-cd-demo.git
    targetRevision: HEAD
  syncPolicy:
    automated:        
      enabled: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jsonPointers:
    - /spec/preserveUnknownFields # K8S will not persist this field, so without ignoring, ArgoCD will always report OutOfSync